name: Linux Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.rst'
      - 'docs/**'
  push:
    paths-ignore:
      - '**.rst'
      - 'docs/**'

jobs:

  javenode:

    name: Javenode
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2

    - name: Setup JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 8

    - name: Build the artifact
      run: gradle build generatePomFileForGeneratePomPublication

    - name: Upload the artifact
      uses: actions/upload-artifact@v3
      with:
        name: javenode
        path: |
          build/libs/*.jar
          build/libs/*.pom
